- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - { role: apt-cli, tags: [ apt-cli ] }
    - { role: color, tags: [ color ] }
    - { role: oh-my-zsh, tags: [ oh-my-zsh ] }
    - { role: tig, tags: [ tig ] }
    - { role: tmux, tags: [ tmux ] }
    - { role: ghq, tags: [ ghq ] }
    - { role: git, tags: [ git ] }
    - { role: percol, tags: [ percol ] }

  vars_prompt:
    - name: "user_name"
      prompt: "Please enter your name (ex. Haruomi Hosono)"
      private: no

    - name: "user_email"
      prompt: "please enter your email address"
      private: no
