apt_packages:
  - { name: ack }
  - { name: ag }
  - { name: ansible }
  - { name: cask }
  - { name: cmigemo }
  - { name: emacs }
  - { name: ghq }
  - { name: gibo }
  - { name: gist }
  - { name: git }
  - { name: go }
  - { name: hg }
  - { name: hub }
  - { name: mosh }
  - { name: node }
  - { name: p7zip }
  - { name: peco }
  - { name: pt }
  - { name: pyenv }
  - { name: rbenv }
  - { name: tig }
  - { name: tmux }
  - { name: vim }
  - { name: wget }
  - { name: zsh }
