dot_vscode: ~/.config/Code/User

packages:
  - ms-python.python
  - lukehoban.Go
  - hiro-sun.vscode-emacs
  - christian-kohler.path-intellisense
  - dbaeumer.vscode-eslint
  - ms-vscode.cpptools
  - waderyan.gitblame
  - ericmccarthy.vs-code-mark-point
  - deerawan.vscode-dash
  - eg2.tslint
  - msjsdiag.debugger-for-chrome

