- name: Installing percol
  pip: name=percol

- name: make ~/.percol.d/
  file: path=~/.percol.d state=directory

- name: copy setting to ~/.percol.d/
  template: src=rc.py dest=~/.percol.d/ mode=0644

- name: copy percol setting to .oh-my-zsh/custom
  template: src=percol.zsh dest=~/.oh-my-zsh/custom/ mode=0644
